export const reducerCases = {
  SET_USER_INFO: "SET_USER_INFO",
  SET_NEW_USER: "SET_NEW_USER",
  SET_ALL_CONTECTS: "SET_ALL_CONTECTS",
  CURRENT_CHAT_USER: "CURRENT_CHAT_USER",
  SET_MESSAGE: "SET_MESSAGE",
  SET_SOCKET: "SET_SOCKET",
  ADD_MESSAGE: "ADD_MESSAGE",
  ALL_MEMBER: "ALL_MEMBER",
  MEMBER_ACTIVE: "MEMBER_ACTIVE",
};
